# Generated by Django 4.2.6 on 2023-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('eventbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
