# Generated by Django 4.2.6 on 2023-10-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbuddy', '0002_alter_event_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='buku',
        ),
    ]
