# Generated by Django 4.2.6 on 2023-10-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('eventbuddy', '0005_alter_event_description_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='book.book'),
        ),
    ]
