# Generated by Django 4.2.6 on 2023-10-28 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventbuddy', '0008_alter_event_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer', models.CharField(max_length=1)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventbuddy.event')),
                ('participant', models.ManyToManyField(null=True, to='main.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
