# Generated by Django 4.2.6 on 2023-10-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('eventbuddy', '0009_regis_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(null=True, to='main.profile'),
        ),
        migrations.DeleteModel(
            name='Regis',
        ),
    ]
