# Generated by Django 4.2.7 on 2023-12-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('mybuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbook',
            name='owned_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
