# Generated by Django 4.2.6 on 2023-10-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachbuddy', '0002_remove_thread_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
