# Generated by Django 4.2.6 on 2024-07-18 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reachbuddy', '0005_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='thread_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
