<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-26 16:25
=======
# Generated by Django 4.2.6 on 2023-10-26 11:21
>>>>>>> cfdcf1ba6a53bd8fe7e526b5fd8409b88848fb10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.CharField(max_length=1)),
                ('profile_picture', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
