# Generated by Django 4.2.6 on 2023-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('etag', models.CharField(max_length=255)),
                ('self_link', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('published_date', models.IntegerField()),
                ('description', models.TextField()),
                ('isbn_13', models.CharField(max_length=13)),
                ('isbn_10', models.CharField(max_length=10)),
                ('page_count', models.IntegerField()),
                ('categories', models.TextField()),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('small_thumbnail', models.URLField(max_length=255)),
                ('thumbnail', models.URLField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('preview_link', models.URLField(max_length=255)),
                ('infoLink', models.URLField(max_length=255)),
                ('country', models.CharField(max_length=3)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyLink', models.URLField(max_length=255)),
                ('webReaderLink', models.URLField(max_length=255)),
                ('accessViewStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
