# Generated by Django 4.2.6 on 2023-10-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findbuddy', '0002_findbook_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FindBook',
        ),
    ]
