# Generated by Django 4.2.4 on 2023-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findbuddy', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookFind',
        ),
    ]
